name: '$(Build.SourceBranchName)$(System.PullRequest.SourceBranch)$(Rev:.r)'

trigger:
  - main
  - feature/*
  - release/*

pr:
  - main
  - releases/*

parameters:
  - name: prDeployment
    type: boolean
    default: true
  - name: branchDeployment
    type: boolean
    default: true
  - name: sndDeployment
    type: boolean
    default: true

resources:
  repositories:
    - repository: templates
      endpoint: DEFRA
      type: github
      name: defra/fcp-pipeline-common
      # ref: branch-name

extends:
  template: fcp-common-pipeline.yaml@templates
  parameters:
    appFrameworkType: nodejs
    prDeployment: ${{ parameters.prDeployment }}
    branchDeployment: ${{ parameters.branchDeployment }}
    sndDeployment: ${{ parameters.sndDeployment }}
    failOnThreshold: moderate  # Optional: moderate (default), low, high, critical
    variableGroupName: ffc-pay-file-receiver-env-var
    pr_params:
      container.fileReceiverEnabled: $(pr_fileReceiverEnabled)
    snd2_params:
      container.fileReceiverEnabled: $(snd2_fileReceiverEnabled)
    dev_params:
      container.fileReceiverEnabled: $(dev_fileReceiverEnabled)
    test_params:
      container.fileReceiverEnabled: $(test_fileReceiverEnabled)
    pre_params:
      container.fileReceiverEnabled: $(pre_fileReceiverEnabled)
    prd_params:
      container.fileReceiverEnabled: $(prd_fileReceiverEnabled)
