services:
  ffc-pay-file-receiver:
    build:
      context: .
      target: production
    image: ffc-pay-file-receiver
    container_name: ffc-pay-file-receiver
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pay-file-receiver-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      FILECONSUME_TOPIC_ADDRESS: ${PUBLISH_TOPIC_ADDRESS:-ffc-pay-file-consume}
      FILECONSUME_SUBSCRIPTION_ADDRESS: ${PUBLISH_SUBSCRIPTION_ADDRESS:-ffc-pay-file-consumer}
      AZURE_STORAGE_BLOB_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME:-devstoreaccount1}
      AZURE_STORAGE_SHARE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME:-}
      AZURE_STORAGE_BLOB_USE_CONNECTION_STRING: "true"
      AZURE_STORAGE_SHARE_USE_CONNECTION_STRING: "true"
      AZURE_STORAGE_SHARE_CONNECTION_STRING: DefaultEndpointsProtocol=https;AccountName=;AccountKey=;EndpointSuffix=core.windows.net
  
  ffc-pay-file-receiver-azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.17.1
    command: "azurite-blob --loose --blobHost 0.0.0.0"
    labels:
      com.docker.compose.pay.role: ffc-pay-file-receiver-azurite
