# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-pay-file-receiver:
    build:
      target: development
    image: ffc-pay-file-receiver-development
    container_name: ffc-pay-file-receiver-development
    ports:
      - "9254:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json

  ffc-pay-file-receiver-azurite:
    volumes:
      - azurite_data:/data
    ports:
      - "10074:10000"

volumes:
  azurite_data:
