services:
  ffc-pay-file-receiver:
    build:
      context: .
      target: production
    image: ffc-pay-file-receiver
    container_name: ffc-pay-file-receiver
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pay-file-receiver-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
