# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-pay-file-receiver:
    build:
      target: development
    image: ffc-pay-file-receiver-development
    container_name: ffc-pay-file-receiver-development
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
    environment:
      AZURE_STORAGE_BLOB_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://ffc-pay-file-receiver-azurite:10000/devstoreaccount1;
      AZURE_STORAGE_SHARE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME:-}${AZURE_STORAGE_SHARE_ACCOUNT_NAME}
      AZURE_STORAGE_SHARE_CONNECTION_STRING: DefaultEndpointsProtocol=https;AccountName=${AZURE_STORAGE_SHARE_ACCOUNT_NAME};AccountKey=${AZURE_STORAGE_SHARE_ACCOUNT_KEY};EndpointSuffix=core.windows.net

  ffc-pay-file-receiver-azurite:
    volumes:
      - azurite_data:/data
    ports:
      - "10073:10000"

volumes:
  azurite_data:
