services:
  ffc-pay-file-receiver:
    build:
      context: .
      target: production
    image: ffc-pay-file-receiver
    container_name: ffc-pay-file-receiver
    environment:
     
  ffc-pay-file-receiver-azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.17.1
    command: "azurite-blob --loose --blobHost 0.0.0.0"
    labels:
      com.docker.compose.pay.role: ffc-pay-file-receiver-azurite
