apiVersion: v2
description: Transfer files from DAX
name: ffc-pay-file-receiver
# this version is automatically updated in the build pipeline
version: 1.0.0
dependencies:
- name: ffc-helm-library
  version: 4.0.0
  repository: https://raw.githubusercontent.com/defra/ffc-helm-repository/master/
