environment: production
environmentCode:
name: ffc-pay-file-receiver
namespace: ffc-pay
workstream: ffc-pay
image: ffc-pay-file-receiver

labels:
  component: service

appInsights:
  key:

containerConfigMap:
  name: ffc-pay-file-receiver-config-map

containerSecret:
  name: ffc-pay-file-receiver-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3000
  messageQueueHost: namespace.servicebus.windows.net
  fileConsumeTopicAddress: ffc-pay-file-consume
  fileConsumeSubscriptionAddress: ffc-pay-file-consumer
  azureStorageShareAccountName: ffcpay
  azureStorageShareUseConnectionString: false
  azureStorageShareConnectionString: dummy
  azureStorageBlobAccountName: ffcpay
  azureStorageBlobUseConnectionString: false
  azureStorageBlobConnectionString: dummy
  azureStorageBlobCreateContainers: false
  storageBlobContainer: dax
  storageBlobFolder: inbound

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5
