environment: development
environmentCode:
name: ffc-pay-file-receiver
namespace: ffc-pay
workstream: ffc-pay
image: ffc-pay-file-receiver

labels:
  component: service

appInsights:
  key:

containerConfigMap:
  name: ffc-pay-file-receiver-config-map

containerSecret:
  name: ffc-pay-file-receiver-container-secret
  type: Opaque

deployment:
  minReplicas: 1
  maxReplicas: 1
  cpuThreshold: 120
  memoryThreshold: 120
  minReadySeconds: 0

container:
  requestMemory: 200Mi
  requestCpu: 200m
  limitMemory: 500Mi
  limitCpu: 500m
  port: 3000
  messageQueueHost: namespace.servicebus.windows.net
  fileConsumeTopicAddress: ffc-pay-file-consume
  fileConsumeSubscriptionAddress: ffc-pay-file-consumer
  azureStorageShareAccountName: ffcpay
  azureStorageShareUseConnectionString: false
  azureStorageShareConnectionString: dummy
  azureStorageBlobAccountName: ffcpay
  azureStorageBlobUseConnectionString: false
  azureStorageBlobConnectionString: dummy
  azureStorageBlobCreateContainers: false
  storageBlobContainer: dax
  storageBlobFolder: inbound

aadPodIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 50
  failureThreshold: 3
  timeoutSeconds: 20

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 50
  failureThreshold: 5
  timeoutSeconds: 20