{{- include "ffc-helm-library.container-secret" (list . "ffc-pay-file-receiver.container-secret") -}}
{{- define "ffc-pay-file-receiver.container-secret" -}}
stringData:
  {{- if .Values.appInsights.key }}
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ quote .Values.appInsights.key }}
  {{- end }}
  AZURE_STORAGE_SHARE_CONNECTION_STRING: {{ quote .Values.container.daxStorageConnectionString }}
  MESSAGE_QUEUE_CONNECTION_STRING: {{ quote .Values.container.messageConnectionString }}
{{- end -}}
