---
environment: production
environmentCode: prd
container:
  messageQueueHost: PRDFFCINFSB1001.servicebus.windows.net
  azureStorageAccountName: prdffcdocst1001
  endpointEnabled: true
  redisHostname: PRDFFCINFRD1001.redis.cache.windows.net
ingress:
  server: azure.defra.cloud
  endpoint: ffc-pay-file-receiver-prd
secretProviderClass:
  azure:
    keyvaultName: PRDFFCINFKV1001
    objects:
      - objectName: prd-ffcahwr-appinsights-connectionString
        objectType: secret
      - objectName: prd-daxStorageConnectionString
        objectType: secret
      - objectName: prd-messageConnectionString
        objectType: secret

  secretObjects:
    - secretName: ffc-pay-file-receiver
      type: Opaque
      data:
        - objectName: prd-ffcahwr-appinsights-connectionString
          key: APPINSIGHTS_CONNECTIONSTRING
        - objectName: prd-daxStorageConnectionString
          key: AZURE_STORAGE_SHARE_CONNECTION_STRING
        - objectName: prd-messageConnectionString
          key: MESSAGE_QUEUE_CONNECTION_STRING